import type { Project, Expense, FilamentPurchase } from '@/types';

export const DEMO_PROJECTS: Project[] = [
  // ── Completed & shipped ─────────────────────────────────────────────────
  {
    id: 'demo-proj-1',
    name: 'Articulated Dragon Statue — Adult Size',
    customerName: 'Carlos R.',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-08-25',
    dueDate: '2026-09-10',
    totalPrice: 95,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-09-10',
    notes: 'Natural grey PLA, 0.12 mm layer height. Articulated joints, no supports needed.',
    kanbanStatus: 'shipped',
    completedAt: '2026-09-08T14:00:00Z',
    paidAt: '2026-09-09T09:30:00Z',
    isRecurringCustomer: true,
    prints: [
      { id: 'demo-proj-1-p1', name: 'Dragon Body', estimatedPrintTime: 480, materialUsed: 210, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#9CA3AF', material: 'PLA', pricePerPiece: 70, colorPalette: ['#9CA3AF'] },
      { id: 'demo-proj-1-p2', name: 'Dragon Wings & Tail', estimatedPrintTime: 180, materialUsed: 95, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#6B7280', material: 'PLA', pricePerPiece: 25, colorPalette: ['#6B7280'] },
    ],
    projectExpenses: [{ id: 'demo-proj-1-e1', name: 'Express shipping', amount: 5.50, category: 'Shipping', notes: '' }],
  },
  {
    id: 'demo-proj-2',
    name: 'D&D Miniature Set — 20 Pieces',
    customerName: 'Sarah K.',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-08-28',
    dueDate: '2026-09-12',
    totalPrice: 78,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-09-11',
    notes: 'Matte black PLA. 28mm heroic scale. Customer provided STL files.',
    kanbanStatus: 'shipped',
    completedAt: '2026-09-10T11:00:00Z',
    paidAt: '2026-09-10T16:00:00Z',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-2-p1', name: 'Miniature Batch — Plate 1', estimatedPrintTime: 360, materialUsed: 95, printer: 'Bambu X1C', status: 'completed', quantity: 10, completedQuantity: 10, color: '#1C1917', material: 'PLA', pricePerPiece: 3.9, colorPalette: ['#1C1917'] },
      { id: 'demo-proj-2-p2', name: 'Miniature Batch — Plate 2', estimatedPrintTime: 360, materialUsed: 95, printer: 'Bambu X1C', status: 'completed', quantity: 10, completedQuantity: 10, color: '#1C1917', material: 'PLA', pricePerPiece: 3.9, colorPalette: ['#1C1917'] },
    ],
    projectExpenses: [{ id: 'demo-proj-2-e1', name: 'Tracked shipping', amount: 4.20, category: 'Shipping', notes: '' }],
  },
  {
    id: 'demo-proj-3',
    name: 'Custom Business Card Holder — Laser Engraved Look',
    customerName: 'Tom B.',
    customerSource: 'Website',
    paymentMethod: 'Bank Transfer',
    orderDate: '2026-08-22',
    dueDate: '2026-09-05',
    totalPrice: 45,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-09-04',
    notes: 'Matte black PETG. Company logo debossed on top panel.',
    kanbanStatus: 'shipped',
    completedAt: '2026-09-03T10:00:00Z',
    paidAt: '2026-09-03T15:00:00Z',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-3-p1', name: 'Card Holder', estimatedPrintTime: 150, materialUsed: 78, printer: 'Bambu P1P', status: 'completed', quantity: 1, completedQuantity: 1, color: '#111827', material: 'PETG', pricePerPiece: 45, colorPalette: ['#111827'] },
    ],
    projectExpenses: [],
  },
  {
    id: 'demo-proj-4',
    name: 'RC Car Body Shell — Ford GT40 Replica',
    customerName: 'Diego M.',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-08-18',
    dueDate: '2026-09-02',
    totalPrice: 65,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-09-01',
    notes: 'ABS dark grey, acetone smoothed finish. 1/10 scale.',
    kanbanStatus: 'shipped',
    completedAt: '2026-08-30T09:00:00Z',
    paidAt: '2026-08-31T11:00:00Z',
    isRecurringCustomer: true,
    prints: [
      { id: 'demo-proj-4-p1', name: 'Body Shell', estimatedPrintTime: 540, materialUsed: 245, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#1F2937', material: 'ABS', pricePerPiece: 50, colorPalette: ['#1F2937'] },
      { id: 'demo-proj-4-p2', name: 'Rear Wing & Spoiler', estimatedPrintTime: 90, materialUsed: 48, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#1F2937', material: 'ABS', pricePerPiece: 15, colorPalette: ['#1F2937'] },
    ],
    projectExpenses: [{ id: 'demo-proj-4-e1', name: 'Tracked shipping + insurance', amount: 6.80, category: 'Shipping', notes: '' }],
  },
  {
    id: 'demo-proj-5',
    name: 'Wedding Cake Topper — Custom Silhouettes',
    customerName: 'Emma & James',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-08-10',
    dueDate: '2026-08-28',
    totalPrice: 120,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-08-27',
    notes: 'White PLA matte. Custom silhouettes from couple photos. Delivered 3 days early!',
    kanbanStatus: 'shipped',
    completedAt: '2026-08-25T13:00:00Z',
    paidAt: '2026-08-26T10:00:00Z',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-5-p1', name: 'Topper Silhouettes + Base', estimatedPrintTime: 210, materialUsed: 92, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#F8FAFC', material: 'PLA', pricePerPiece: 120, colorPalette: ['#F8FAFC'] },
    ],
    projectExpenses: [{ id: 'demo-proj-5-e1', name: 'Gift box + ribbon', amount: 4.50, category: 'Other', notes: '' }],
  },
  {
    id: 'demo-proj-6',
    name: 'Desk Cable Management Kit — 3-Piece Set',
    customerName: 'HomeOffice Solutions',
    customerSource: 'Website',
    paymentMethod: 'Bank Transfer',
    orderDate: '2026-08-05',
    dueDate: '2026-08-22',
    totalPrice: 42,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-08-21',
    notes: 'Black PETG. Cable spine, desk clamp, and cable box. Business order.',
    kanbanStatus: 'shipped',
    completedAt: '2026-08-20T15:00:00Z',
    paidAt: '2026-08-20T17:30:00Z',
    isRecurringCustomer: true,
    prints: [
      { id: 'demo-proj-6-p1', name: 'Cable Management Box', estimatedPrintTime: 240, materialUsed: 115, printer: 'Bambu P1P', status: 'completed', quantity: 1, completedQuantity: 1, color: '#111827', material: 'PETG', pricePerPiece: 28, colorPalette: ['#111827'] },
      { id: 'demo-proj-6-p2', name: 'Cable Spine + Clamp', estimatedPrintTime: 90, materialUsed: 42, printer: 'Bambu P1P', status: 'completed', quantity: 2, completedQuantity: 2, color: '#111827', material: 'PETG', pricePerPiece: 7, colorPalette: ['#111827'] },
    ],
    projectExpenses: [],
  },
  {
    id: 'demo-proj-7',
    name: 'Architectural Scale Model — Porch & Façade',
    customerName: 'Studio Arch',
    customerSource: 'Website',
    paymentMethod: 'Bank Transfer',
    orderDate: '2026-07-25',
    dueDate: '2026-08-15',
    totalPrice: 145,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-08-14',
    notes: 'White PLA+ 1:50 scale. Three plates — walls, roof, details. For client presentation.',
    kanbanStatus: 'shipped',
    completedAt: '2026-08-12T16:00:00Z',
    paidAt: '2026-08-13T09:00:00Z',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-7-p1', name: 'Walls & Foundation', estimatedPrintTime: 720, materialUsed: 280, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#F1F5F9', material: 'PLA', pricePerPiece: 80, colorPalette: ['#F1F5F9'] },
      { id: 'demo-proj-7-p2', name: 'Roof & Canopy', estimatedPrintTime: 360, materialUsed: 125, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#F1F5F9', material: 'PLA', pricePerPiece: 45, colorPalette: ['#F1F5F9'] },
      { id: 'demo-proj-7-p3', name: 'Facade Details', estimatedPrintTime: 180, materialUsed: 48, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#F1F5F9', material: 'PLA', pricePerPiece: 20, colorPalette: ['#F1F5F9'] },
    ],
    projectExpenses: [{ id: 'demo-proj-7-e1', name: 'Rigid foam base board', amount: 8.00, category: 'Other', notes: '' }],
  },
  {
    id: 'demo-proj-8',
    name: 'Plant Pot Collection — 4 Geometric Designs',
    customerName: 'Green Thumb Boutique',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-07-22',
    dueDate: '2026-08-10',
    totalPrice: 85,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-08-09',
    notes: 'Terracotta-coloured PLA. Geometric faceted design. Boutique reseller order.',
    kanbanStatus: 'shipped',
    completedAt: '2026-08-07T12:00:00Z',
    paidAt: '2026-08-08T10:00:00Z',
    isRecurringCustomer: true,
    prints: [
      { id: 'demo-proj-8-p1', name: 'Pots x4 (batched)', estimatedPrintTime: 600, materialUsed: 470, printer: 'Bambu P1P', status: 'completed', quantity: 4, completedQuantity: 4, color: '#C2410C', material: 'PLA', pricePerPiece: 21.25, colorPalette: ['#C2410C'] },
    ],
    projectExpenses: [{ id: 'demo-proj-8-e1', name: 'Packaging + bubble wrap', amount: 5.00, category: 'Shipping', notes: '' }],
  },

  // ── In progress — all due dates in the future ─────────────────────────
  {
    id: 'demo-proj-9',
    name: 'Iron Man MkIV Helmet — Full Size',
    customerName: 'Jake P.',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-09-05',
    dueDate: '2026-09-28',
    totalPrice: 180,
    printed: false,
    paid: false,
    sent: false,
    shippingDate: '',
    notes: 'Metallic red + gold PLA. Full wearable size. Two-tone multi-colour print.',
    kanbanStatus: 'printing',
    completedAt: '',
    paidAt: '',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-9-p1', name: 'Helmet Main Shell', estimatedPrintTime: 900, materialUsed: 385, printer: 'Bambu X1C', status: 'printing', quantity: 1, completedQuantity: 0, color: '#DC2626', material: 'PLA', pricePerPiece: 130, colorPalette: ['#DC2626', '#CA8A04'] },
      { id: 'demo-proj-9-p2', name: 'Faceplate & Chin Guard', estimatedPrintTime: 360, materialUsed: 145, printer: 'Bambu X1C', status: 'not-printed', quantity: 1, completedQuantity: 0, color: '#CA8A04', material: 'PLA', pricePerPiece: 50, colorPalette: ['#CA8A04'] },
    ],
    projectExpenses: [],
  },
  {
    id: 'demo-proj-10',
    name: 'Artisan Keycap Set — 12 Custom Sculpts',
    customerName: 'KeyboardCraft',
    customerSource: 'Website',
    paymentMethod: 'Bank Transfer',
    orderDate: '2026-09-08',
    dueDate: '2026-09-22',
    totalPrice: 55,
    printed: true,
    paid: false,
    sent: false,
    shippingDate: '',
    notes: 'PLA Silk Gold. 12 unique sculpt designs. Ready to ship, awaiting payment.',
    kanbanStatus: 'finished',
    completedAt: '2026-09-15T11:00:00Z',
    paidAt: '',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-10-p1', name: 'Keycap Set', estimatedPrintTime: 320, materialUsed: 88, printer: 'Bambu X1C', status: 'completed', quantity: 12, completedQuantity: 12, color: '#CA8A04', material: 'PLA', pricePerPiece: 4.58, colorPalette: ['#CA8A04'] },
    ],
    projectExpenses: [],
  },
  {
    id: 'demo-proj-11',
    name: 'Modular Wall Organizer System',
    customerName: 'Maria L.',
    customerSource: 'Website',
    paymentMethod: 'Bizum',
    orderDate: '2026-09-14',
    dueDate: '2026-10-06',
    totalPrice: 38,
    printed: false,
    paid: false,
    sent: false,
    shippingDate: '',
    notes: 'Black PETG. 3-column grid system with shelf hooks and cable channels.',
    kanbanStatus: 'new-order',
    completedAt: '',
    paidAt: '',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-11-p1', name: 'Organizer Grid Panels x3', estimatedPrintTime: 420, materialUsed: 220, printer: 'Bambu P1P', status: 'not-printed', quantity: 3, completedQuantity: 0, color: '#111827', material: 'PETG', pricePerPiece: 12.67, colorPalette: ['#111827'] },
    ],
    projectExpenses: [],
  },
];

export const DEMO_EXPENSES: Expense[] = [
  { id: 'demo-exp-1', date: '2026-09-01', name: 'September Electricity Bill', category: 'Equipment', amount: 28.50, notes: 'Monthly workshop power' },
  { id: 'demo-exp-2', date: '2026-08-20', name: 'Bambu Lab Hardened Steel Nozzle Kit', category: 'Equipment', amount: 18.00, notes: '0.4 mm × 2 packs' },
  { id: 'demo-exp-3', date: '2026-09-05', name: 'Packaging Supplies — Boxes & Bubble Wrap', category: 'Shipping', amount: 15.60, notes: 'Mixed box sizes, 50 pack bubble bags' },
  { id: 'demo-exp-4', date: '2026-07-30', name: 'Photon Wash & Cure Station', category: 'Equipment', amount: 89.00, notes: 'One-time equipment purchase' },
  { id: 'demo-exp-5', date: '2026-08-08', name: 'Prusa Smooth PEI Sheet', category: 'Equipment', amount: 24.00, notes: 'Replacement print surface' },
];

export const DEMO_FILAMENT: FilamentPurchase[] = [
  { id: 'demo-fil-1', purchaseDate: '2026-07-10', materialType: 'PLA+', brand: 'eSUN', spoolWeight: 1000, numberOfSpools: 2, totalCost: 39.98, notes: 'Grey & natural — stock restock' },
  { id: 'demo-fil-2', purchaseDate: '2026-07-10', materialType: 'PLA+', brand: 'eSUN', spoolWeight: 1000, numberOfSpools: 1, totalCost: 19.99, notes: 'White — for architectural models' },
  { id: 'demo-fil-3', purchaseDate: '2026-07-28', materialType: 'PLA Matte', brand: 'Bambu Lab', spoolWeight: 1000, numberOfSpools: 1, totalCost: 24.99, notes: 'Jade white — miniatures & toppers' },
  { id: 'demo-fil-4', purchaseDate: '2026-08-05', materialType: 'PETG', brand: 'eSUN', spoolWeight: 1000, numberOfSpools: 2, totalCost: 44.98, notes: 'Black PETG — functional parts & organizers' },
  { id: 'demo-fil-5', purchaseDate: '2026-08-12', materialType: 'ABS', brand: 'Polymaker', spoolWeight: 1000, numberOfSpools: 1, totalCost: 21.99, notes: 'Dark grey — RC bodies, post-process friendly' },
  { id: 'demo-fil-6', purchaseDate: '2026-08-25', materialType: 'PLA Silk', brand: 'eSUN', spoolWeight: 1000, numberOfSpools: 1, totalCost: 21.99, notes: 'Gold — keycaps and decorative prints' },
  { id: 'demo-fil-7', purchaseDate: '2026-09-03', materialType: 'TPU 95A', brand: 'Bambu Lab', spoolWeight: 500, numberOfSpools: 1, totalCost: 28.99, notes: 'Flexible black — protective cases and grips' },
];

export const DEMO_FILAMENT_COST = DEMO_FILAMENT.reduce((s, fp) => s + fp.totalCost, 0);
