import type { Project, Expense, FilamentPurchase } from '@/types';

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'demo-proj-1',
    name: 'Dragon Miniature Set',
    customerName: 'Carlos R.',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-04-10',
    dueDate: '2026-04-20',
    totalPrice: 45,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-04-18',
    notes: 'High detail, 0.1mm layer height. Natural grey PLA.',
    kanbanStatus: 'shipped',
    completedAt: '2026-04-17T10:00:00Z',
    paidAt: '2026-04-18T08:00:00Z',
    isRecurringCustomer: true,
    prints: [
      { id: 'demo-proj-1-p1', name: 'Dragon Body', estimatedPrintTime: 240, materialUsed: 85, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#9CA3AF', material: 'PLA', pricePerPiece: 35, colorPalette: ['#9CA3AF'] },
      { id: 'demo-proj-1-p2', name: 'Dragon Wings', estimatedPrintTime: 90, materialUsed: 30, printer: 'Bambu X1C', status: 'completed', quantity: 1, completedQuantity: 1, color: '#6B7280', material: 'PLA', pricePerPiece: 10, colorPalette: ['#6B7280'] },
    ],
    projectExpenses: [{ id: 'demo-proj-1-e1', name: 'Shipping', amount: 3.5, category: 'Shipping', notes: '' }],
  },
  {
    id: 'demo-proj-2',
    name: 'Custom Phone Stand',
    customerName: 'Maria L.',
    customerSource: 'Wallapop',
    paymentMethod: 'Bizum',
    orderDate: '2026-04-28',
    dueDate: '2026-05-05',
    totalPrice: 18,
    printed: true,
    paid: true,
    sent: true,
    shippingDate: '2026-05-04',
    notes: '',
    kanbanStatus: 'paid',
    completedAt: '2026-05-03T16:00:00Z',
    paidAt: '2026-05-04T09:00:00Z',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-2-p1', name: 'Phone Stand', estimatedPrintTime: 75, materialUsed: 42, printer: 'Ender 3', status: 'completed', quantity: 1, completedQuantity: 1, color: '#1D4ED8', material: 'PETG', pricePerPiece: 18, colorPalette: ['#1D4ED8'] },
    ],
    projectExpenses: [],
  },
  {
    id: 'demo-proj-3',
    name: 'Cable Organizer Box',
    customerName: 'David M.',
    customerSource: 'Website',
    paymentMethod: 'Bank Transfer',
    orderDate: '2026-05-12',
    dueDate: '2026-05-26',
    totalPrice: 25,
    printed: false,
    paid: false,
    sent: false,
    shippingDate: '',
    notes: 'Black PETG. Lid with label slot.',
    kanbanStatus: 'printing',
    completedAt: '',
    paidAt: '',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-3-p1', name: 'Organizer Box', estimatedPrintTime: 180, materialUsed: 120, printer: 'Bambu P1P', status: 'printing', quantity: 1, completedQuantity: 0, color: '#111827', material: 'PETG', pricePerPiece: 20, colorPalette: ['#111827'] },
      { id: 'demo-proj-3-p2', name: 'Box Lid', estimatedPrintTime: 45, materialUsed: 30, printer: 'Bambu P1P', status: 'not-printed', quantity: 1, completedQuantity: 0, color: '#111827', material: 'PETG', pricePerPiece: 5, colorPalette: ['#111827'] },
    ],
    projectExpenses: [],
  },
  {
    id: 'demo-proj-4',
    name: 'Earring Display Stand',
    customerName: 'Ana G.',
    customerSource: 'Instagram',
    paymentMethod: 'PayPal',
    orderDate: '2026-05-18',
    dueDate: '2026-05-30',
    totalPrice: 32,
    printed: false,
    paid: false,
    sent: false,
    shippingDate: '',
    notes: 'White PLA, 3-tier design. Include gift box.',
    kanbanStatus: 'new-order',
    completedAt: '',
    paidAt: '',
    isRecurringCustomer: true,
    prints: [
      { id: 'demo-proj-4-p1', name: 'Display Stand', estimatedPrintTime: 210, materialUsed: 95, printer: 'Bambu X1C', status: 'not-printed', quantity: 1, completedQuantity: 0, color: '#F9FAFB', material: 'PLA', pricePerPiece: 32, colorPalette: ['#F9FAFB'] },
    ],
    projectExpenses: [{ id: 'demo-proj-4-e1', name: 'Gift box', amount: 2, category: 'Other', notes: '' }],
  },
  {
    id: 'demo-proj-5',
    name: 'Toy Car Replacement Parts',
    customerName: 'Roberto K.',
    customerSource: 'Other',
    paymentMethod: 'Cash',
    orderDate: '2026-05-08',
    dueDate: '2026-05-15',
    totalPrice: 20,
    printed: true,
    paid: false,
    sent: false,
    shippingDate: '',
    notes: 'Red ABS wheels x4 + axle cover.',
    kanbanStatus: 'finished',
    completedAt: '2026-05-14T14:00:00Z',
    paidAt: '',
    isRecurringCustomer: false,
    prints: [
      { id: 'demo-proj-5-p1', name: 'Toy Wheels', estimatedPrintTime: 110, materialUsed: 60, printer: 'Ender 3', status: 'completed', quantity: 4, completedQuantity: 4, color: '#DC2626', material: 'ABS', pricePerPiece: 4, colorPalette: ['#DC2626'] },
      { id: 'demo-proj-5-p2', name: 'Axle Cover', estimatedPrintTime: 20, materialUsed: 10, printer: 'Ender 3', status: 'completed', quantity: 1, completedQuantity: 1, color: '#1F2937', material: 'ABS', pricePerPiece: 4, colorPalette: ['#1F2937'] },
    ],
    projectExpenses: [],
  },
];

export const DEMO_EXPENSES: Expense[] = [
  { id: 'demo-exp-1', date: '2026-05-01', name: 'eSUN PLA+ White 1kg', category: 'Filament', amount: 22, notes: 'AliExpress order' },
  { id: 'demo-exp-2', date: '2026-04-15', name: 'Bambu Lab Build Plate Adhesive', category: 'Equipment', amount: 12, notes: '' },
  { id: 'demo-exp-3', date: '2026-05-10', name: 'DHL Packaging Supplies', category: 'Shipping', amount: 8.5, notes: 'Bubble wrap and boxes' },
];

export const DEMO_FILAMENT: FilamentPurchase[] = [
  { id: 'demo-fil-1', purchaseDate: '2026-04-01', materialType: 'PLA+', brand: 'eSUN', spoolWeight: 1000, numberOfSpools: 2, totalCost: 37.98, notes: 'Grey and white' },
  { id: 'demo-fil-2', purchaseDate: '2026-04-20', materialType: 'PLA Matte', brand: 'Bambu Lab', spoolWeight: 1000, numberOfSpools: 1, totalCost: 24.99, notes: 'Black' },
  { id: 'demo-fil-3', purchaseDate: '2026-05-05', materialType: 'PETG', brand: 'eSUN', spoolWeight: 1000, numberOfSpools: 1, totalCost: 22.5, notes: 'Transparent blue' },
];

export const DEMO_FILAMENT_COST = DEMO_FILAMENT.reduce((s, fp) => s + fp.totalCost, 0);
